In [2]:
import numpy as np
import matplotlib

In [9]:
A = np.ones((4, 5))
B = np.arange(0, 20).reshape((4, 5))

In [11]:
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
np.sum(B, axis=1)

array([10, 35, 60, 85])